from enum import Enum

CONTRACTION: str = 'CONTRACTION'
SAMPLING:str = 'SAMPLING'
class MeasureMethod(Enum):
    CONTRACTION = "CONTRACTION"
    SAMPLING = "SAMPLING"
    EFFICIENT_CONTRACTION = "EFFICIENT_CONTRACTION"
    CORRECT_SAMPLING = "CORRECT_SAMPLING"