from enum import Enum

FULL_CONTRACTION: str = 'FULL_CONTRACTION'
PERFECT_SAMPLING: str = 'PERFECT_SAMPLING'
class MeasureMethod(Enum):
    FULL_CONTRACTION = "FULL_CONTRACTION"
    PERFECT_SAMPLING = "PERFECT_SAMPLING"
    EFFICIENT_CONTRACTION = "EFFICIENT_CONTRACTION"
    RIGHT_SUFFIX_SAMPLING = "RIGHT_SUFFIX_SAMPLING"